### ISSUE TITLE
Seemingly unused parameter in platform _XNAT

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-xnat#144]
At first glance, the `platform._XNAT` class has a `cmd_param` named `collection` which is not referenced at all within the class definition (or the file which defines it). Is it a holdover from a previous approach, preparation for something to be done, or something which is used elsewhere? Alternatively, I could have just missed something.

https://github.com/datalad/datalad-xnat/blob/16f30ab0e36d5a055f01c0cc5ed36d3d70a05a59/datalad_xnat/platform.py#L89-L96

**Comment by mih** [comment]
I am closing this issue, because all these args are used in init and update. This class is just the place where they presently live.

I guess a comment could be added.
