### ISSUE TITLE
Register CI with https://github.com/datalad/datalad-extensions

### ISSUE THREAD

**Issue by mih** [datalad/datalad-xnat#15]

**Comment by adswa** [comment]
I'll start a PR on this. I will likely open it as a draft against the extensions repository and update as necessary until we have released

**Comment by adswa** [comment]
Submitted a PR against it: https://github.com/datalad/datalad-extensions/pull/93 Can hopefully be merged after the first release.

**Comment by mih** [comment]
Done, now! Thx!
