### ISSUE TITLE
Create an extension Logo for the docs 

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-xnat#26]
[datalad-osf](http://docs.datalad.org/projects/osf/en/latest/) has a logo - a non-coding contribution could be the design of a logo for datalad-xnat

**Comment by jsheunis** [comment]
@adswa is the idea to have a logo similar to this one: https://github.com/datalad/datalad-osf/blob/master/docs/source/_static/git-annex-osf-logo.png

i.e. with the "box" part remaining, but with XNAT replacing OSF?

If so, do you know if there is a source image for the "box" part somewhere?

**Comment by adswa** [comment]
Against all odds, I found it: https://github.com/datalad-handbook/artwork/blob/68157e300eae18cc8846c71a4930dae83597d17e/src/closedbox.svg

**Comment by adswa** [comment]
But any logo is fine, feel free to implement any idea :)
