### ISSUE TITLE
allow for the selection of specific acquisitions for download

### ISSUE THREAD

**Issue by loj** [datalad/datalad-xnat#27]
Right now I can  query and download specific XNAT projects and subjects, but sometimes it would be helpful to be able to this for specific acquisitions/sessions as well.

Currently, `xnat-update` will download all acquisitions for a given subject ID under the configured project. If I only want to download a selection of acquisitions for this subject, I need to manually edit the addurls table created by `xnat-update` to only include the sessions that I want.

Perhaps we could add an additional option to `xnat-update` that allows one to indicate specific sessions for download, i.e. 
```
datalad xnat-update -d. --subjects S01234 --sessions E54321 E54322
```

**Comment by mih** [comment]
FTR: A "session" in this context is an XNAT "experiment"

**Comment by mih** [comment]
All that is left todo now, is to amend the API of xnat-update to allow for that.
