### ISSUE TITLE
Verify and implement CI test for NITRC IR

### ISSUE THREAD

**Issue by mih** [datalad/datalad-xnat#29]
This is a modified XNAT instance that ships other data types than DICOM.

Here is a possible public dataset to test against:

https://www.nitrc.org/ir/app/action/DisplayItemAction/search_element/xnat%3AprojectData/search_field/xnat%3AprojectData.ID/search_value/fcon_1000

**Comment by jhuguetn** [comment]
FYI,
Any XNAT instance (no modification required) can coarsely handle imaging data types other than DICOM (eg. see [CENTRAL05_E03795](https://central.xnat.org/data/experiments/CENTRAL05_E03795?format=html)).  
That's actually one of the reasons why `pyxnat` requires [browsing Resources](https://github.com/datalad/datalad-xnat/issues/32) for each Scan entity before moving down and track scan Files (multiple formats of the imaging data may co-exist as resources). 

Hope it helps. Good luck with the project, such an interesting initiative.

**Comment by mih** [comment]
Thanks for the feedback!

**Comment by mih** [comment]
With #48 I can query a NITRC IR project, but the download fails:

```
addurls(error): /tmp/nitrc/xnat_S01288/xnat_E01288/anat_mprage_anonymized/scan_mprage_anonymized.nii.gz (file) [AnnexBatchCommandError(AnnexBatchCommandError: 'addurl' [Error, annex reported failure for addurl (url='https://www.nitrc.org/data/experiments/xnat_E01288/scans/anat_mprage_anonymized/resources/7900/files/scan_mprage_anonymized.nii.gz'): {'command': 'addurl', 'success': False, 'input': ['https://www.nitrc.org/data/experiments/xnat_E01288/scans/anat_mprage_anonymized/resources/7900/files/scan_mprage_anonymized.nii.gz xnat_S01288/xnat_E01288/anat_mprage_anonymized/scan_mprage_anonymized.nii.gz'], 'error-messages': ['  download failed: Not Found'], 'file': 'xnat_S01288/xnat_E01288/anat_mprage_anonymized/scan_mprage_anonymized.nii.gz'}])]
```

Seems to be the same issue as #47, but in the table generation.
