### ISSUE TITLE
Set up all-contributors bot to credit contributions

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-xnat#38]
In datalad-osf we used @all-contributors (I bet the bot will come around and respond after I post this). It is a nice way of acknowledging contributions in open source projects. 

I propose to set it up for this project as well. Documentation on how to do it is [here](https://allcontributors.org/docs/en/bot/installation), but it may require the right set of permissions, so whoever takes this issue on, please get in touch if you need anything. :)

**Comment by jsheunis** [comment]
@all-contributors please add @mih for code bug doc ideas maintenance

**Comment by jsheunis** [comment]
@adswa It seemed like I was able to add the bot to this repo, but looks like it's not responding after the above comment. So perhaps it wasn't added and only sent a request to someone with more permissions. Can you check if you can see a notification about this and if it requires an action?

**Comment by jsheunis** [comment]
Let's try again

@all-contributors please add @mih for code bug doc ideas maintenance

**Comment by jsheunis** [comment]
@all-contributors please add @loj for code bug ideas maintenance

**Comment by jsheunis** [comment]
@all-contributors please add @adswa for code bug doc ideas maintenance

**Comment by jsheunis** [comment]
@all-contributors please add @jwodder for code ideas

**Comment by jsheunis** [comment]
@all-contributors please add @yarikoptic for code

**Comment by jsheunis** [comment]
Closing this issue since setup is complete. Let's add contributors on their specific issues, or otherwise we can add in bulk later on a new issue. @adswa please reopen if you disagree.

**Comment by adswa** [comment]
hey @all-contributors please add @jsheunis for infra

**Comment by adswa** [comment]
@aqw provided tech support for @oportoles yesterday. Hey @all-contributors please add @aqw for question
