### ISSUE TITLE
`update` prompts for user input of XNAT url when creating subdatasets

### ISSUE THREAD

**Issue by loj** [datalad/datalad-xnat#4]
In #2,  `xnat-init` calls the configuration procedure `cfg_xnat_dataset.py` to setup the XNAT server authentication and enable the datalad special remote for the root dataset.

`xnat-update` calls the same configuration procedure with `addurls` in order to configure subdatasets. But, because the configuration procedure is unaware of the configured XNAT url in the root dataset's config (that is provided with `xnat-init`), it prompts the user to provide it each time a subdataset is created. This is not desirable.

Possible solutions:

1. Use the environment variable, `DATALAD_XNAT_DEFAULT_URL`, with `xnat-update`
2. Have `cfg_xnat_dataset.py` create a separate configuration procedure to be used with `addurls` that:
  a. is a copy of the existing procedure, but with the XNAT url already populated or
  b. copies the the authentication config file from the root dataset using `copy-file`

**Comment by mih** [comment]
I think your proposal (1) makes sense and can be implemented minimally invasive (by patching `os.environ` for the runtime of `addurls`.
