### ISSUE TITLE
Add a contributor CODE OF CONDUCT

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-xnat#66]
A starting point is to use the template from datalad-handbook:
https://github.com/datalad-handbook/book/blob/master/CODE_OF_CONDUCT.md

If more recent updates or examples are applicable, please feel free to link them below and/or submit a PR.

After the CoC is added, ensure that correct link is added to the README and Welcome Bot (#59 )

**Comment by CinnamonXI** [comment]
Please can you assign this task to me?

**Comment by adswa** [comment]
Hey @CinnamonXI thanks for getting in touch! I believe that this task was already done in #70 (@jsheunis, please correct me if I am mistaken). Maybe you can find a different issue, if you are still interested in contributing? Something that wouldn't involve much coding, for example, could be to add a few sentences to the documentation, If you are up for it, you could include a short answer to the question "What is XNAT" in the section http://docs.datalad.org/projects/datalad-xnat/en/latest/intro.html in the docs

**Comment by jsheunis** [comment]
Indeed, the task of adding the Code of Conduct has already been done (sorry!)

I think @adswa's suggestion is a great alternative, though.

**Comment by CinnamonXI** [comment]
Oh, thank you.
I will work on this one you just suggested then.

**Comment by adswa** [comment]
Awesome, @CinnamonXI! Today is day 2 of a hackathon that we use to work on this tool. If you want to hang out with us, we will be on gathertown today, and also reachable via Matrix chat. The gathertown link is in the room description of https://matrix.to/#/!FCQCvvKiiCtpccpBuS:matrix.org?via=matrix.org&via=matrix.waite.eu&via=inm7.de. Let me know if you need any help; you can ping any contributor to this repo in issues if you need help

**Comment by CinnamonXI** [comment]
Okay, thanks

**Comment by jsheunis** [comment]
One additional step that's necessary here is to mention the CoC in the README and/or a new CONTRIBUTING.md file (to be created)

**Comment by adswa** [comment]
> One additional step that's necessary here is to mention the CoC in the README and/or a new CONTRIBUTING.md file (to be created)

I think we can transform this into a standalone issue, and close this one.
