### ISSUE TITLE
Test the welcome bot by opening an issue (if you haven't opened one yet)

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-xnat#94]
We're looking for someone who hasn't contributed to this repository (i.e., also hasn't opened any issues yet) to test the functionality of our welcome bot.
The task would simply be to open a new issue. The content is completely irrelevant, you could also just name it "test for the bot" - Thanks in advance to whoever takes this on!

**Comment by aqw** [comment]
Confirmed working in #102
